# Entrace Example for AI Builders

จุดมุ่งหมายคือการทดสอบความรู้ปรับพื้นฐานสำหรับ AI Builders ทุกคำตอบสามารถหาได้จาก notebook ปรับพื้นฐาน `ai_builder_intro_python.ipynb`, `ai_builder_numpy.ipynb` และ `ai_builder_pandas.ipynb` 

เราหวังให้คุณพยามสุดความสามารถที่จะตอบ แต่ไม่จำเป็นต้องตอบได้ครบทุกข้อเพื่อที่จะได้รับการคัดเลือกเข้าโครงการ

## Python

1. หาก `a=1` และ `b=2.5` แล้ว, `c` = $0.5(a+2b^5)$, `c` มีค่าเท่าไหร่? $b^x$ เขียนใน Python ได้แบบนี้ `b**x`

In [ ]:
a = 1
b = 2.5
c = 0.5 * (a+(2*b**5))
c

98.15625

2. `a`, `b`, และ `c` เป็นตัวแปรชนิดอะไรบ้าง? (ลองใช้ `type(a)`)

In [ ]:
# a เป็น int 
# b เป็น float
# c เป็น float

3. จากตัวแปร `s = 'AI Builders - A Program For Kids Who Wants to AI Good Good'`, เราจะดึงคำว่า `AI Good` ออกมาได้อย่างไร?

In [ ]:
s = 'AI Builders - A Program For Kids Who Wants to AI Good Good'

s.split(' ')[10] + ' ' +s.split(' ')[11]


'AI Good'

4. ใช้ loop `print` ทุก element ใน `l` ยกเว้น element ที่เขียนว่า `AI`

`l = ['AI','Builders','-','A','Program','For','Kids','Who','Wants','to','AI','Good','Good']`

ลองใช้ `for` และ `if` เพื่อกรอง element ที่มีค่าเป็น `AI` ออก

In [ ]:
l = ['AI','Builders','-','A','Program','For','Kids','Who','Wants','to','AI','Good','Good']
for i in l :
  if i == 'AI' :
    l.remove(i)
l

['Builders',
 '-',
 'A',
 'Program',
 'For',
 'Kids',
 'Who',
 'Wants',
 'to',
 'Good',
 'Good']

5. เขียนฟังชั่น `midpoint` ที่หาจุดกึ่งกลางระหว่างตัวเลข `a` และ `b` 

In [ ]:
def midpoint(a, b):


  return (a + b)/2


print(midpoint(1, 4))  # expected 2.5
print(midpoint(3, 3))  # expected 3
print(midpoint(-2, 2))  # expected 0

2.5
3.0
0.0


6. เขียนฟังชั่น `fizzbuzz` ที่รับตัวเลข `x`


- ถ้า `x` หารด้วย 2 ลงให้คืน string ว่า `fizz`
- ถ้า `x` หารด้วย 3 ลงให้คืน string ว่า `buzz`
- ถ้า `x` หารด้วยทั้ง 2 และ 3 ลงให้คืน string ว่า `fizzbuzz`
- นอกนั้นให้คืน `None`

ลองใช้ `if`, `elif` และ `else` ในฟังชั่น `fizzbuzz`

In [ ]:
def fizzbuzz(x):
    if x % 2 == 0 and x % 3 ==0 :
      return 'fizzbuzz'
    elif x % 2 == 0 :
      return 'fizz' 
    elif x % 3 == 0 :
      return 'buzz'

for i in range(20):
    print(i,fizzbuzz(i))

0 fizzbuzz
1 None
2 fizz
3 buzz
4 fizz
5 None
6 fizzbuzz
7 None
8 fizz
9 buzz
10 fizz
11 None
12 fizzbuzz
13 None
14 fizz
15 buzz
16 fizz
17 None
18 fizzbuzz
19 None


## Numpy and Linear Algebra

In [ ]:
import numpy as np

1. สร้าง numpy array `a` ที่มีมิติ `3*3` โดยมีค่าเป็นตัวเลขจาก 1 ถึง 9 (ลองใช้ `np.arange` และ `np.reshape`)

In [ ]:
a =  np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2. สร้าง numpy array `b` ที่มีมิติ `4*3` โดยมีค่าเป็นตัวเลขจาก 1 ถึง 12 (ลองใช้ `np.arange` และ `np.reshape`)

In [ ]:
b = np.arange(1,13).reshape (4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

3. เราสามารถหาค่า `a` dot product `b` ได้หรือไม่-เพราะอะไร (ลองใช้ `a.dot(b)` หรือ `a@b`)

In [ ]:
# ไม่ได้ เพราะ a กับ b ไม่เป็นไปตามกฏของการคูณของเมทริกซ์ ถ้าจะให้ได้หลักของ a ต้อง เท่ากับ แถว ของ b กรณีนี้เป็น 3 กับ 4 จึงไม่ได้ 


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

4. หาค่า `a` dot product (`b` transposed) (tranpose `b` ได้ด้วยคำสั่ง `b.T`)

In [ ]:
a.dot(b.T)


array([[ 14,  32,  50,  68],
       [ 32,  77, 122, 167],
       [ 50, 122, 194, 266]])

5. มิติ (แถวและคอลัมน์) ของ `a` และ `b` คืออะไร (ลองใช้ `a.shape`)

In [ ]:
# มิติ คือ ขนาดของข้อมูล เช่น 1 มิติ , 2 มิติ , 3 มิติ (มากสุดคือ 3)
# ในมิติ จะมีการจัดวางข้อมูลในรูปแบบของ แถว และ คอลัมน์ หรือ แนวนอน และ แนวตังนั่นเอง
# ตัวอย่าง 1 มิติ [1,2,3] 
# ตัวอย่าง 2 มิติ [1,2,3],
#             [4,5,6]
# ตัวอย่าง 3 มิติ [1,2,3],
#             [4,5,6],
#             [7,8,9]
b.shape


(4, 3)

6. คูณทุก element ของ `a` ด้วย -1

In [ ]:
a*-1

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

7. เปลี่ยนมิติของ `b` ให้เป็น `2*2*3` (ลองใช้ `np.reshape`)

In [ ]:
b.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

8. ค่าเฉลี่ยของแต่ละแถวของ `a` (`3*3`) คืออะไร (ลองใช้ `np.mean` สังเกตว่าควรใช้ `axis=1` หรือ `axis=0`)

In [ ]:
a.mean(axis=1)

array([2., 5., 8.])

9. ค่าเฉลี่ยของแต่ละคอลัมน์ของ `a` (`3*3`) คืออะไร (ลองใช้ `np.mean` สังเกตว่าควรใช้ `axis=1` หรือ `axis=0`)

In [ ]:
a.mean(axis=0)

array([4., 5., 6.])

10. ถ้าเราต้องการหา `[[1,2],[4,5]]` จาก `a` เราต้องเลือกอย่างไร

In [ ]:
#เราสามารถ slice แต่ละส่วนของ `np.array` ได้เหมือนกับ list เช่น 
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

## Pandas and Data Exploration

ดาวน์โหลดชุดข้อมูล [อุบัติเหตุบนโครงข่ายถนนของกระทรวงคมนาคม 2562](https://data.go.th/dataset/roadaccident) (ไฟล์ชื่อ `ubatiehtuthaangthnn.xlsx`) จาก [data.go.th](https://data.go.th/). ตอบคำถามต่อไปนี้

In [8]:
import pandas as pd

1. อ่านไฟล์ `ubatiehtuthaangthnn.xlsx` เข้ามาเป็น `pandas.DataFrame`; `df` มีกี่แถว-คอลัมน์? (ลองใช้ `df.shape`)

In [42]:
url = 'https://archive.org/download/ubatiehtuthaangthnn/ubatiehtuthaangthnn.xlsx'
df = pd.read_excel(url)

df.shape


(19965, 20)

2. เรียกดู 20 แถวแรกและ 20 แถวสุดท้ายของ `df` (ลองใช้ `df.head(20)` และ `df.tail(20)`)

In [10]:
df.head(20).append(df.tail(20))

ปีที่เกิดเหตุ วันที่เกิดเหตุ   เวลา  ...  สภาพอากาศ   LATITUDE   LONGITUDE
0               2019     01/01/2019  00:00  ...     แจ่มใส  14.959105  100.873463
1               2019     01/01/2019  00:03  ...     แจ่มใส  15.210738  104.862689
2               2019     01/01/2019  00:05  ...     แจ่มใส  12.374259   99.907949
3               2019     01/01/2019  00:20  ...     แจ่มใส  18.601721   98.804204
4               2019     01/01/2019  00:25  ...     แจ่มใส  15.866389  100.590010
5               2019     01/01/2019  00:30  ...     แจ่มใส   9.949354   99.063479
6               2019     01/01/2019  00:30  ...  หมอก/ควัน  18.815921   97.920940
7               2019     01/01/2019  00:35  ...     แจ่มใส  14.894032  100.396529
8               2019     01/01/2019  00:40  ...     แจ่มใส   7.059981  100.173978
9               2019     01/01/2019  00:45  ...     แจ่มใส  12.322957  102.552188
10              2019     01/01/2019  00:45  ...     แจ่มใส   9.984233   99.067814
11              2019     01/01/2019  00:45  ...  หมอก/ควัน  18.599324   99.042958
12              2019     01/01/2019  01:00  ...     แจ่มใส  14.627897  100.889634
13              2019     01/01/2019  01:00  ...     แจ่มใส   7.842125   98.334675
14              2019     01/01/2019  01:00  ...     แจ่มใส  13.574613   99.829910
15              2019     01/01/2019  01:04  ...     แจ่มใส  14.225988  100.704656
16              2019     01/01/2019  01:15  ...     แจ่มใส  14.573909  100.965667
17              2019     01/01/2019  01:20  ...     แจ่มใส  15.129263  102.274953
18              2019     01/01/2019  01:20  ...     แจ่มใส  12.373410   99.910510
19              2019     01/01/2019  01:30  ...     แจ่มใส   8.157798   99.845810
19945           2019     31/12/2019  22:20  ...     แจ่มใส  14.821608  103.064552
19946           2019     31/12/2019  22:20  ...     แจ่มใส  16.860865  104.681361
19947           2019     31/12/2019  22:26  ...     แจ่มใส   7.824511   98.342547
19948           2019     31/12/2019  22:30  ...     แจ่มใส   7.735923   99.301866
19949           2019     31/12/2019  22:30  ...     แจ่มใส  14.409696   99.839236
19950           2019     31/12/2019  22:38  ...     แจ่มใส  15.199799  103.924889
19951           2019     31/12/2019  22:40  ...  หมอก/ควัน  14.853877  100.064163
19952           2019     31/12/2019  22:40  ...     แจ่มใส  14.475853  100.110649
19953           2019     31/12/2019  22:40  ...     แจ่มใส  17.296240  102.861399
19954           2019     31/12/2019  22:40  ...     แจ่มใส  14.569187  100.236908
19955           2019     31/12/2019  23:00  ...     แจ่มใส  13.165411   99.842039
19956           2019     31/12/2019  23:10  ...     แจ่มใส   8.812859   99.166543
19957           2019     31/12/2019  23:20  ...     แจ่มใส  12.951183  100.958457
19958           2019     31/12/2019  23:20  ...     แจ่มใส  18.589153   99.042735
19959           2019     31/12/2019  23:30  ...     แจ่มใส  18.858869   99.105689
19960           2019     31/12/2019  23:30  ...     แจ่มใส  15.171119   98.462388
19961           2019     31/12/2019  23:35  ...     แจ่มใส   8.092608   98.811692
19962           2019     31/12/2019  23:40  ...  หมอก/ควัน   9.939225   98.633500
19963           2019     31/12/2019  23:40  ...     แจ่มใส  18.829234   99.006029
19964           2019     31/12/2019  23:45  ...     แจ่มใส  13.588040  100.788317

[40 rows x 20 columns]

3. จังหวัดใดมีอุบัติเหตุเยอะที่สุดถ้าอ้างอิงจาก `df`? (ลองใช้ `df['จังหวัด'].value_counts()`)

In [11]:
# กรุงเทพมหานคร
df['จังหวัด'].value_counts().head(1)


กรุงเทพมหานคร    1844
Name: จังหวัด, dtype: int64

4. เลือกเฉพาะแถวที่เป็นอุบัติเหตุที่มีผู้เสียชีวิต 0 ราย / มีอุบัติเหตุที่ไม่มีผู้เสียชีวิตกี่ครั้ง? (เราสามารถกรอง dataframe ได้ด้วยคำสั่ง `df[df['จำนวนผู้เสียชีวิต']==0]`)

In [43]:
df.rename(columns={'จำนวนผู้เสียชวิต':'จำนวนผู้เสียชีวิต'},inplace=True)
x = df[df['จำนวนผู้เสียชีวิต']==0]
x['จำนวนผู้เสียชีวิต'].value_counts()
# 17296 ครั้ง

0    17296
Name: จำนวนผู้เสียชีวิต, dtype: int64

5. ค่าเฉลี่ยของ latitude, logitude ของอุบัติเหตุที่เกิดขึ้นในจังหวัดเชียงใหม่อยู่ที่เท่าใด? (กรองให้เหลือแค่จังหวัดเชียงใหม่แล้วหาค่าเฉลี่ยด้วยคำสั่ง `df.LATITUDE.mean()` และ `df.LONGITUDE.mean()`)

In [13]:
y= df[df['จังหวัด']=='เชียงใหม่']
print('('+ str(y.LATITUDE.mean()) + ', ' + str(y.LONGITUDE.mean()) + ')' )

(18.91090138416936, 98.91462670826341)


6. `ลักษณะการเกิดอุบัติเหตุ ` แบบใดมี `จำนวนผู้เสียชวิต` โดยเฉลี่ยสูงที่สุด?

In [40]:
#Hint 1: df[COLUMN_NAME].value_counts().reset_index() will give you dataframe version of value counts
#Hint 2: See what sort_values() does

x = df.iloc[:,[13,15]]
x.columns = ['ลักษณะการเกิดอุบัติเหตุ','จำนวนผู้เสียชีวิต']

####################################
xx = x.groupby(['ลักษณะการเกิดอุบัติเหตุ'])
xxx = xx.mean()
xxx.sort_values(['จำนวนผู้เสียชีวิต'],ascending=0).reset_index()


ลักษณะการเกิดอุบัติเหตุ  จำนวนผู้เสียชีวิต
0                                     ชนรถไฟ           6.000000
1                                   ชนขณะแซง           0.794118
2                       รถยนต์พลิกคว่ำ ตกถนน           0.750000
3     รถจักรยานยนต์ชนรถจักรยานพลิกคว่ำ ตกถนน           0.750000
4        ชนในทิศทางตรงกันข้าม (ไม่ใช่การแซง)           0.615385
5                               ชนคนเดินเท้า           0.610714
6                      ชนกัน/ชนยานพาหนะอื่นๆ           0.437209
7                                    ชนรถจอด           0.436548
8                                    ตกจากรถ           0.428571
9                          รถจักรยานยนต์ชนคน           0.400000
10                     ชนเป็นมุมบริเวณทางแยก           0.385135
11            รถยนต์ชนรถจักรยานยนต์/รถสามล้อ           0.250000
12                         ชนกันหรือเฉี่ยวชน           0.232843
13                     รถยนต์ชนวัตถุ สิ่งของ           0.172414
14                             ชนสิ่งกีดขวาง           0.161616
15                              เลี้ยว/ถอยชน           0.157895
16                                    ชนท้าย           0.154588
17                                  เฉี่ยวชน           0.152490
18                              รถยนต์ชนรถไฟ           0.148148
19      รถจักรยานยนต์ชนกับรถจักรยาน รถสามล้อ           0.142857
20                                  ชนขอบทาง           0.128889
21                                    อื่น ๆ           0.128205
22                             พลิกคว่ำตกถนน           0.106300
23           เสียหลัก ไปอยู่ในช่องจราจรอื่นๆ           0.080128
24  ชนตู้เก็บเงิน ไม้กั้นเลน อุปกรณ์เก็บเงิน           0.052632
25                           ชนอุปกรณ์งานทาง           0.047334
26           รถยนต์ชนสัตว์ รถลากจูงด้วยสัตว์           0.035714
27                               รถยนต์ชนกัน           0.000000
28                     รถจักรยานยนต์ชนรถยนต์           0.000000
29                                  พลิกคว่ำ           0.000000

07. อุบัติเหตุที่เกิดจาก `มูลเหตุสันนิษฐาน` เป็น `ขับรถเร็วเกินกำหนด` มีโอกาสทำให้มีผู้เสียชีวิตมากกว่า `มูลเหตุสันนิษฐาน` อื่นหรือไม่?

In [45]:
#สร้าง column `drive_fast_flag` ที่จะเป็น 1 เมื่อ 'มูลเหตุสันนิษฐาน' เป็น 'ขับรถเร็วเกินกำหนด' (นอกนั้นเป็น 0) โดยใช้ map และ lambda
df['drive_fast_flag'] = df['มูลเหตุสันนิษฐาน'].map(lambda x: 1 if x=='ขับรถเร็วเกินกำหนด' else 0)

#สร้าง column `has_death` ที่จะเป็น 1 เมื่อ 'จำนวนผู้เสียชีวิต' มากกว่า 1 คน (นอกนั้นเป็น 0) โดยใช้ map และ lambda
df['has_death'] = df['จำนวนผู้เสียชีวิต'].map(lambda x: 1 if x>= 1 else 0)
#ใช้ groupby('drive_fast_flag').has_death.mean() เพื่อหาค่าเฉลี่ยของอุบัติเหตุที่มีผู้เสียชีวิต แบ่งด้วย drive_fast_flag
df.groupby('drive_fast_flag').has_death.mean()

drive_fast_flag
0    0.157192
1    0.124128
Name: has_death, dtype: float64